/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_msu_cme_rdp_alignment_hmm_jni_HMMER3 */

#ifndef _Included_edu_msu_cme_rdp_alignment_hmm_jni_HMMER3
#define _Included_edu_msu_cme_rdp_alignment_hmm_jni_HMMER3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_msu_cme_rdp_alignment_hmm_jni_HMMER3
 * Method:    initHmmer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT int JNICALL Java_edu_msu_cme_rdp_alignment_hmm_jni_HMMER3_initHmmer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_msu_cme_rdp_alignment_hmm_jni_HMMER3
 * Method:    destroyHmmer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_msu_cme_rdp_alignment_hmm_jni_HMMER3_destroyHmmer
  (JNIEnv *, jobject);

/*
 * Class:     edu_msu_cme_rdp_alignment_hmm_jni_HMMER3
 * Method:    hmmer3
 * Signature: (Ljava/lang/String;, [Ledu/msu/cme/rdp/alignment/hmm/jni/HMMER3Hit;)I
 */
JNIEXPORT jobjectArray JNICALL Java_edu_msu_cme_rdp_alignment_hmm_jni_HMMER3_hmmer3
(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
